mod panel;
mod svg_icon;
mod authentication;
mod home;
mod login;
mod preferences;
mod input;
mod menu_item;
mod icon_button;
mod collapse_panel;
mod sidebar;
mod dashboard_view;
mod dashboard;
mod card;
mod text_button;
mod playlist_view;
mod breadcrumbs;
mod playlist;
mod table;
mod toggle_switch;

pub use self::svg_icon::*;
// pub use self::input::*;
// pub use self::menu_item::*;
pub use self::icon_button::*;
pub use self::text_button::*;
pub use self::panel::*;
pub use self::card::*;
pub use self::collapse_panel::*;
pub use self::authentication::*;
pub use self::login::*;
pub use self::home::*;
pub use self::sidebar::*;
pub use self::preferences::*;
pub use self::dashboard_view::*;
pub use self::dashboard::*;
pub use self::playlist_view::*;
pub use self::breadcrumbs::*;
pub use self::playlist::*;
pub use self::table::*;
pub use self::toggle_switch::*;
