name: Rust Build rust-wasm-tools

on:
  workflow_dispatch:
  push:
    paths:
      - docker/build-tools/rust-wasm-tools.Dockerfile
      - .github/workflows/rust-wasm-tools-prebuild.yml
  workflow_run:
    workflows:
      - Rust Bump trunk & wasm-bindgen-cli
    types: [completed]

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/rust-wasm-tools

jobs:
  precheck:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.diff.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || '' }}
          fetch-depth: 2
      - id: diff
        run: |
          set -e
          if git diff --name-only HEAD^ HEAD | grep -q '^docker/build-tools/rust-wasm-tools\.Dockerfile$'; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"
          fi

  build:
    needs: precheck
    if: needs.precheck.outputs.should_run == 'true' && (github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success')
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
            tag: linux-amd64
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
            tag: linux-arm64
          - platform: linux/arm/v7
            runner: ubuntu-22.04-arm
            tag: linux-armv7

    runs-on: ${{ matrix.runner || 'ubuntu-22.04' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || '' }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build & push ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/build-tools/rust-wasm-tools.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ matrix.tag }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-${{ matrix.tag }}
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache-${{ matrix.tag }},mode=max

  manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push multi-arch manifest :latest
        run: |
          IMAGE=${{ env.IMAGE_NAME }}
          docker buildx imagetools create -t ${IMAGE}:latest \
            ${IMAGE}:linux-amd64 \
            ${IMAGE}:linux-arm64 \
            ${IMAGE}:linux-armv7
      - name: Inspect manifest
        run: docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest
