name: Build & Push rust-wasm-tools (prebuild)

on:
  workflow_dispatch:
    inputs:
      trunk_ver:
        description: "trunk version"
        required: false
      bindgen_ver:
        description: "wasm-bindgen-cli version"
        required: false

env:
  IMAGE: ghcr.io/${{ github.repository }}/rust-wasm-tools

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            tag: linux-amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            tag: linux-arm64
          - platform: linux/arm/v7         # build armv7 on arm64 runner (fast cross-compile)
            runner: ubuntu-24.04-arm
            tag: linux-armv7

    runs-on: ${{ matrix.runner || 'ubuntu-24.04' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platform }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push single-arch image; Dockerfile cross-compiles in the builder stage
      - name: Build & Push (${{ matrix.platform }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/build-tools/rust-wasm-tools.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ matrix.tag }}
          cache-from: type=gha,scope=tools-${{ matrix.tag }}
          cache-to:   type=gha,mode=max,scope=tools-${{ matrix.tag }}

      - name: Inspect image
        run: docker buildx imagetools inspect "${IMAGE}:${{ matrix.tag }}"

      # Pull platform-specific image and read label versions
      - name: Pull & inspect image labels
        id: img
        shell: bash
        env:
          IMG: ${{ env.IMAGE }}:${{ matrix.tag }}
          PLAT: ${{ matrix.platform }}
        run: |
          set -euo pipefail

          # Pull the platform-specific image (quiet); do not fail the job if missing
          set +e
          PULL_LOG="$(docker pull -q --platform "$PLAT" "$IMG" 2>&1)"
          RC=$?
          set -e

          if [ $RC -eq 0 ]; then
            echo "published=true" >> "$GITHUB_OUTPUT"
          else
            echo "published=false" >> "$GITHUB_OUTPUT"
            {
              echo "pull_error<<__EOF__"
              echo "$PULL_LOG"
              echo "__EOF__"
            } >> "$GITHUB_OUTPUT"
          fi

          # Read version labels (may be empty if image missing or labels not set)
          TRUNK="$(docker image inspect -f '{{ index .Config.Labels "io.tuliprox.trunk.version"}}' "$IMG" 2>/dev/null || true)"
          BINDGEN="$(docker image inspect -f '{{ index .Config.Labels "io.tuliprox.wasm_bindgen.version"}}' "$IMG" 2>/dev/null || true)"

          echo "trunk_version=${TRUNK:-unknown}" >> "$GITHUB_OUTPUT"
          echo "bindgen_version=${BINDGEN:-unknown}" >> "$GITHUB_OUTPUT"

      # Summary (uses values from the step above)
      - name: Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## rust-wasm-tools \`${{ matrix.tag }}\`"
            echo ""
            echo "🖼️ Image: \`${{ env.IMAGE }}:${{ matrix.tag }}\`"
            echo "🧭 Platform: \`${{ matrix.platform }}\`"
            echo ""
            if [[ "${{ steps.img.outputs.published }}" == "true" ]]; then
              echo "✅ Published and pulled"
            else
              echo "❌ Not found / pull failed"
              if [[ -n "${{ steps.img.outputs.pull_error }}" ]]; then
                echo ""
                echo "<details><summary>Pull error</summary>"
                echo ""
                echo '```'
                echo "${{ steps.img.outputs.pull_error }}"
                echo '```'
                echo "</details>"
              fi
            fi
            echo "🔧 trunk: **${{ steps.img.outputs.trunk_version }}**"
            echo "🔧 wasm-bindgen: **${{ steps.img.outputs.bindgen_version }}**"
            echo ""
            echo "---"
          } >> "$GITHUB_STEP_SUMMARY"


  manifest:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Buildx (required for imagetools)
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch :latest manifest
        id: create
        run: |
          IMAGE="${{ env.IMAGE }}"
          docker buildx imagetools create \
            -t "${IMAGE}:latest" \
            "${IMAGE}:linux-amd64" \
            "${IMAGE}:linux-arm64" \
            "${IMAGE}:linux-armv7"

      - name: Inspect :latest manifest
        run: docker buildx imagetools inspect "${{ env.IMAGE }}:latest"

      # Final summary for the manifest
      - name: Summary (:latest)
        if: always()
        shell: bash
        run: |
          {
            echo "## rust-wasm-tools \`:latest\` manifest"
            if [[ "${{ steps.create.outcome }}" == "success" ]]; then
              echo "✅ Multi-arch manifest created:"
              echo "- linux-amd64"
              echo "- linux-arm64"
              echo "- linux-armv7"
              echo ""
              echo "📦 Tag: \`${{ env.IMAGE }}:latest\`"
            else
              echo "❌ Failed to create multi-arch \`:latest\` manifest."
            fi
          } >> "$GITHUB_STEP_SUMMARY"
